[tool.black]
line-length = 120
target-version = ["py38", "py39", "py310", "py311"]
include = "\\.pyi?$"
workers = 4

[tool.mypy]
strict = true
pretty = true
show_error_codes = true
show_error_context = true
show_column_numbers = true
warn_unused_configs = true
color_output = true

namespace_packages = true
explicit_package_bases = true

# ignores for dependencies without type information
[[tool.mypy.overrides]]
module = [
    "ansible.*",
]
ignore_missing_imports = true
