name: CI
on:
  push:
    branches:
      - main
      - stable-*
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:
  docsite:
    name: Lint extra docsite docs and links
    permissions:
      contents: read
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install antsibull-docs
        run: pip install antsibull-docs --disable-pip-version-check

      - name: Run collection docs linter
        run: antsibull-docs lint-collection-docs .

  formatting:
    name: Formatting (black)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install black
        shell: bash
        run: |
          set -eux
          cat requirements.txt | grep "black==" | xargs pip install

      - name: Run black
        shell: bash
        run: |
          set -eux
          black --check --diff .

  mypy:
    name: Type checks (mypy)
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install requirements
        shell: bash
        run: |
          set -eux
          pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Link repo into the correct structure and run mypy
        shell: bash
        run: |
          set -eux
          mkdir -p collection_root/ansible_collections/cloud
          ln -s ../../.. collection_root/ansible_collections/cloud/terraform
          cd collection_root/ansible_collections/cloud/terraform/
          export MYPYPATH="$PWD/../../../"
          mypy -p ansible_collections.cloud.terraform.plugins

  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
    strategy:
      matrix:
        ansible:
          - stable-2.13
          - stable-2.14
        python:
          - '3.8'
          - '3.9'
          - '3.10'
    runs-on: ubuntu-20.04
    steps:
      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          testing-type: sanity
          ansible-core-version: ${{ matrix.ansible }}
          target-python-version: ${{ matrix.python }}

  units:
    runs-on: ubuntu-20.04
    name: Units (Ⓐ${{ matrix.ansible }})
    strategy:
      fail-fast: true
      matrix:
        ansible:
          - stable-2.13
          - stable-2.14
    steps:
      - name: >-
          Perform unit testing against
          Ansible version ${{ matrix.ansible }}
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: units
          target-python-version: "3.10"

  integration:
    runs-on: ubuntu-20.04
    name: Integration (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }}+tf${{ matrix.terraform }})
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - stable-2.13
          - stable-2.14
        python:
          - '3.8'
          - '3.9'
          - '3.10'
        terraform:
          - "1.3.4"
        exclude:
          # ansi2.14 requires py>=3.9
          - ansible: stable-2.14
            python: '3.8'
    steps:
      # we want to force tests to run locally, not in docker, so we replace --docker with --local forcefully
      # a bit of a hack but what can you do
      - name: Provision the ansible-test arg filtering script
        run: |
          mkdir -p ~/.local/bin/
          cat >~/.local/bin/ansible-test-filtered <<EOF
          #!/bin/sh
          set -eux
          args="\$(echo "\$*" | sed "s/--docker/--local/")"
          exec ~/.local/bin/ansible-test-actual \$args
          EOF
          
          chmod +x ~/.local/bin/ansible-test-filtered
          cat ~/.local/bin/ansible-test-filtered
        shell: bash

      # we use raw git to create a repository in the tests
      # this fails if the committer doesn't have a name and an email set
      - name: Set up git
        run: |
          git config --global user.email gha@localhost
          git config --global user.name "Github Actions"
        shell: bash

      - name: >-
          Perform integration testing against
          Ansible version ${{ matrix.ansible }}
          under Python ${{ matrix.python }}
          with Terraform ${{ matrix.terraform }}
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          origin-python-version: ${{ matrix.python }}
          target-python-version: ${{ matrix.python }}
          testing-type: integration
          target: --exclude gcp --exclude aws --exclude azure
          pre-test-cmd: |-
            pip install coverage
            
            curl -L https://releases.hashicorp.com/terraform/${{ matrix.terraform }}/terraform_${{ matrix.terraform }}_linux_amd64.zip | zcat > terraform
            chmod +x terraform
            sudo mv terraform /usr/bin/terraform

            mv ~/.local/bin/ansible-test ~/.local/bin/ansible-test-actual
            mv ~/.local/bin/ansible-test-filtered ~/.local/bin/ansible-test
